ALTER TABLE products ADD COLUMN updated_at TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE settings ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
